apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-2
  name: nginx-2
spec:
  containers:
  - image: shryu1/test:33
    name: nginx
    ports:
    - containerPort: 80
  imagePullSecrets:
  - name: shryu
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx-2
  name: nginx-svc-2
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-2
  type: ClusterIP
